### ISSUE TITLE
`make upload` is not macOS compatible

### ISSUE THREAD

**Issue by ubgk** [upkie/upkie#152]
The current Makefile is not macOS compatible. Right now, I use a remote Ubuntu machine to build the project and use `rsync` to synchronise the build with my local environment. 

When I try to do `make upload`:

1. The variable `CURDATE` uses GNU `date`, which is different from the macOS `date`: https://github.com/tasts-robots/upkie/blob/34c27ec31381abfad95fed486c3c47fd87d76284/Makefile#L30 I therefore needed to install the compatible binary on macOS using `brew`: https://stackoverflow.com/a/9805125. 
2. The `upload` recipe triggers the build, which fails on macOS currently. This step should probably be adjusted accordingly once #150 is solved to take remote builds into account.

**Comment by stephane-caron** [comment]
> The upload recipe triggers the build, which fails on macOS currently.

This is because the `build` rule is a prerequisite for the `upload` rule in the Makefile. It's more of a double check (make sure we always upload the latest build) written with the assumption that the build and upload systems would be the same.

We don't have a hard constraint on this, feel free to remove the `build` prerequisite from `upload` if that fixes it on your :apple:.

**Comment by stephane-caron** [comment]
Closing this issue as running `make upload` should not be necessary any more on the client side.
