### ISSUE TITLE
[CI] Workflows fail

### ISSUE THREAD

**Issue by ubgk** [upkie/upkie#438]
Existing PRs seem to fail due to: 
- a Doxygen error despite not making any changes in the error-causing file (i.e., #436 and #437). Also, the current Doxygen version is reported as `1.9.8` whereas for the last successful build, it was `1.9.1`.
- pip install error: https://github.com/upkie/upkie/actions/runs/11282799633/job/31381013410#step:2:1

The seemingly irrelevant failures appearing at the same time makes me suspect there was a change in a *shared* and *non-versioned* in a dependency that likely caused warnings to turn into errors. 

~The runner image versions are also slightly different between the [last successful run](https://github.com/upkie/upkie/actions/runs/11240354135) and now: `24.04.1` vs `24.04.5`, so maybe some `apt` packages also changed in-between ?~

*Update*: This seems to be a project configuration related issue, rather than the runners themselves. I couldn't reproduce the issue against my own fork.

**Comment by stephane-caron** [comment]
That's right, thanks for checking. Doxygen was updated and now it catches more documentation errors. Some of those errors were actually relevant :smiley: But some others are related to (welcome) updates in how Doxygen 1.10.0 parses Python classes. We notably run into https://github.com/doxygen/doxygen/issues/10670 which will apparently be fixed in Doxygen 1.11.0, while the current version on conda-forge is 1.10.0.

I suggest we switch to installing Doxygen from conda-forge anyway, this way we can specify the exact version we use: https://github.com/upkie/upkie/pull/442
